import Foundation

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case chinese = "zh"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .english: "English"
        case .chinese: "中文"
        }
    }

    func text(_ english: String) -> String {
        guard self == .chinese else { return english }
        return Self.chineseTranslations[english] ?? english
    }

    func format(_ english: String, _ arguments: CVarArg...) -> String {
        String(format: text(english), arguments: arguments)
    }

    private static let chineseTranslations: [String: String] = [
        "OK": "确定",
        "Cancel": "取消",
        "Insert": "插入",
        "Folder": "当前目录",
        "Recent": "最近打开",
        "Drop to open": "放下即可打开",
        "Markdown files only": "仅支持 Markdown 文件",
        "Markdown and image files": "支持 Markdown 与图片文件",
        "Search folder": "搜索当前目录",
        "Clear Search": "清除搜索",
        "New from Markdown Starter (⌘N)": "从 Markdown 模板新建 (⌘N)",
        "New Document (⌘N)": "新建文档 (⌘N)",
        "Open Folder (⇧⌘O)": "打开文件夹 (⇧⌘O)",
        "Open File (⌘O)": "打开文档 (⌘O)",
        "Appearance Settings": "外观设置",
        "Check for Updates": "检查更新",
        "Checking for Updates…": "正在检查更新…",
        "%@ available": "%@ 可更新",
        "MarkV %@ is up to date": "MarkV %@ 已是最新版本",
        "Open the %@ release page": "打开 %@ 发布页面",
        "Update check failed. Click to try again.": "检查更新失败，点击重试。",
        "Close Outline": "关闭大纲",
        "Resize Outline": "调整大纲宽度",
        "Add headings to build an outline.": "添加标题后将在这里生成大纲。",
        "DIRECTORY": "当前目录",
        "Refresh": "刷新",
        "Choose a folder": "选择文件夹",
        "No Markdown files here": "此文件夹中没有 Markdown 文件",
        "No matching documents": "没有匹配的文档",
        "No recently opened files": "没有最近打开的文件",
        "Remove from Recent": "从最近打开中移除",
        "Open File": "打开文档",
        "Copy File Path": "拷贝文件路径",
        "Move to Trash": "移到废纸篓",
        "Move %@ to Trash?": "要将 %@ 移到废纸篓吗？",
        "This file will be moved to the Trash.": "此文件将被移到废纸篓。",
        "Markv could not move the file to Trash: %@": "Markv 无法将文件移到废纸篓：%@",
        "Empty document": "空文档",
        "A quiet place for Markdown.": "安静地阅读和书写 Markdown。",
        "Open a folder to begin.": "打开文件夹开始使用。",
        "Choose a document from the sidebar.": "从左侧选择一个文档。",
        "Open Folder": "打开文件夹",
        "Untitled": "未命名",
        "File name": "文件名",
        "Double-click to rename": "双击重命名",
        "Double-click to rename this file": "双击即可重命名此文件",
        "Focus": "专注",
        "Typewriter": "打字机",
        "Hide Outline": "隐藏大纲",
        "Show Outline": "显示大纲",
        "Save": "保存",
        "Paragraph": "正文",
        "Heading %d": "标题 %d",
        "Text": "文本",
        "Bold (⌘B)": "粗体 (⌘B)",
        "Italic (⌘I)": "斜体 (⌘I)",
        "Strikethrough": "删除线",
        "Inline Code": "行内代码",
        "Blockquote": "引用",
        "Bullet List": "无序列表",
        "Numbered List": "有序列表",
        "Task List": "任务列表",
        "Insert Link": "插入链接",
        "Insert Image": "插入图片",
        "Image URL…": "图片 URL…",
        "Upload Image…": "上传图片…",
        "Upload Image": "上传图片",
        "Upload": "上传",
        "Open or create a Markdown document before importing images.": "请先打开或创建 Markdown 文档，再导入图片。",
        "Choose an image file.": "请选择图片文件。",
        "Images larger than 25 MB are not supported.": "暂不支持大于 25 MB 的图片。",
        "Markv could not import the image: %@": "Markv 无法导入图片：%@",
        "Insert Table": "插入表格",
        "Code Block": "代码块",
        "Horizontal Rule": "分隔线",
        "%d words": "%d 词",
        "%d characters · %d lines · %d min read": "%d 字符 · %d 行 · 阅读约 %d 分钟",
        "Reveal in Finder": "在访达中显示",
        "Appearance": "外观",
        "Choose the reading surface": "选择阅读与写作界面",
        "Language": "语言",
        "Interface language": "界面语言",
        "Writing": "写作",
        "Markdown Files": "Markdown 文件",
        "Open .md files with MarkV by default": "默认使用 MarkV 打开 .md 文件",
        "Default App": "默认应用",
        "Set as Default": "设为默认应用",
        "macOS may ask for confirmation before changing this setting.": "更改此设置前，macOS 可能会请求确认。",
        "macOS did not change the Markdown default application.": "macOS 未更改 Markdown 默认应用。",
        "Markv could not change the Markdown file association: %@": "Markv 无法更改 Markdown 文件关联：%@",
        "Focus mode": "专注模式",
        "Typewriter mode": "打字机模式",
        "AI Extension": "AI 扩展",
        "Enable AI": "启用 AI",
        "OpenAI-compatible API": "兼容 OpenAI 的 API",
        "Base URL": "Base URL",
        "Model": "模型",
        "API Key": "API Key",
        "Optional for local services": "本地服务可留空",
        "API key is stored in macOS Keychain and sent only to the configured endpoint.": "API Key 仅存储在 macOS Keychain，并只发送到配置的服务地址。",
        "Select text and use the sparkle menu, or type / in an empty paragraph.": "选中文本后使用闪光菜单，或在空段落中输入 /。",
        "AI": "AI",
        "Improve Writing": "优化表达",
        "Fix Spelling & Grammar": "修正拼写与语法",
        "Make Shorter": "缩短内容",
        "Make Longer": "扩写内容",
        "Custom Instruction…": "自定义指令…",
        "Enable AI in Settings first.": "请先在设置中启用 AI。",
        "Select text before using AI editing.": "请先选择需要 AI 编辑的文本。",
        "The selected text is too long for AI editing.": "选中的文本过长，无法进行 AI 编辑。",
        "Enter an instruction for AI.": "请输入 AI 指令。",
        "The AI instruction is too long.": "AI 指令过长。",
        "AI request failed: %@": "AI 请求失败：%@",
        "Enter a valid HTTP or HTTPS AI Base URL.": "请输入有效的 HTTP 或 HTTPS AI Base URL。",
        "Enter an AI model name.": "请输入 AI 模型名称。",
        "API keys require HTTPS unless the endpoint is localhost.": "除 localhost 外，AI 服务必须使用 HTTPS。",
        "HTTP AI endpoints are allowed only for localhost.": "HTTP AI 服务仅允许使用 localhost，其他地址必须使用 HTTPS。",
        "The AI service returned an invalid response.": "AI 服务返回了无效响应。",
        "The AI service returned empty content.": "AI 服务返回了空内容。",
        "Markv could not save the API key: %@": "Markv 无法保存 API Key：%@",
        "AI instruction": "AI 指令",
        "How should AI edit the selected text?": "希望 AI 如何修改选中的文本？",
        "What should AI write?": "希望 AI 写什么？",
        "Generate": "生成",
        "AI is working…": "AI 正在处理…",
        "Cancel Request": "取消请求",
        "AI Suggestion": "AI 建议",
        "Original": "原文",
        "Suggested": "建议版本",
        "Replace": "替换",
        "Insert Below": "插入到下方",
        "Try Again": "重新生成",
        "Discard": "放弃",
        "Khaki": "卡其色",
        "White": "白色",
        "Warm paper": "温暖纸张",
        "Clean neutral": "简洁中性",
        "New from Markdown Starter…": "从 Markdown 模板新建…",
        "New Document…": "新建文档…",
        "Open File…": "打开文件…",
        "Open Folder…": "打开文件夹…",
        "Export as PDF…": "导出为 PDF…",
        "Focus Mode": "专注模式",
        "Typewriter Mode": "打字机模式",
        "Format": "格式",
        "Bold": "粗体",
        "Italic": "斜体",
        "Insert Link…": "插入链接…",
        "Insert Image…": "插入图片…",
        "Choose a Markdown folder": "选择 Markdown 文件夹",
        "Open a Markdown file": "打开 Markdown 文件",
        "Open": "打开",
        "That folder is no longer available.": "该文件夹已不可用。",
        "Markv could not read this folder: %@": "Markv 无法读取此文件夹：%@",
        "Enter a valid file name without path separators.": "请输入不含路径分隔符的有效文件名。",
        "A file named %@ already exists.": "名为 %@ 的文件已存在。",
        "Markv could not rename the file: %@": "Markv 无法重命名文件：%@",
        "That recent file is no longer available.": "该最近文件已不可用。",
        "Drop a Markdown file (.md, .markdown, .mdown, or .mkd) to open it.": "请拖入 Markdown 文件（.md、.markdown、.mdown 或 .mkd）。",
        "Export as PDF": "导出为 PDF",
        "Export": "导出",
        "Markv could not export the PDF: %@": "Markv 无法导出 PDF：%@",
        "The print operation did not create a PDF file.": "打印操作未能创建 PDF 文件。",
        "New from Markdown Starter": "从 Markdown 模板新建",
        "New Document": "新建文档",
        "Create": "创建",
        "The template must be saved as a Markdown file.": "模板必须保存为 Markdown 文件。",
        "The document must be saved as a Markdown file.": "文档必须保存为 Markdown 文件。",
        "Markv could not create the template: %@": "Markv 无法创建模板：%@",
        "Markv could not create the document: %@": "Markv 无法创建文档：%@",
        "Markv could not save %@: %@": "Markv 无法保存 %@：%@",
        "Markv can open Markdown files only.": "Markv 只能打开 Markdown 文件。",
        "Markv could not open %@: %@": "Markv 无法打开 %@：%@",
        "Save changes to %@?": "要保存对 %@ 的修改吗？",
        "Your edits will be lost if you don't save them.": "如果不保存，所做的修改将会丢失。",
        "Don't Save": "不保存",
        "Insert link": "插入链接",
        "Insert image URL or relative path": "插入图片网址或相对路径",
        "Start writing…": "开始写作…",
        "Type Markdown naturally…": "自然地输入 Markdown…"
    ]
}
